---
- name: Deploy MongoDB service using Docker
  docker_container:
    name: mongodb
    image: "{{ db_image }}"
    state: started
    ports:
      - "27017:27017"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ db_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ db_password }}"
