version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
